default_stages: [pre-commit]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.8
    hooks:
      - id: ruff
        exclude: bulk_processing/workers/celery_app.py
        name: ruff-lint
        args: [ --fix, --exit-non-zero-on-fix, --show-fixes, -v, "--line-length", "88" ]

      - id: ruff-format
        args: [ -v ]