default_stages: [pre-commit]

repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.2
    hooks:
      - id: poetry-check
        name: poetry-check

      - id: poetry-export
        name: poetry-export
        args: [ -f, requirements.txt, --output, requirements.txt, --without-hashes]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.8
    hooks:
      - id: ruff
        name: ruff-lint
        args: [ --fix, --exit-non-zero-on-fix, --show-fixes, -v ]

      - id: ruff-format
        args: [ -v ]