[tool.poetry]
name = "karanta"
version = "0.1.0"
description = ""
authors = ["TARESCO"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.2.3"
pdf2image = "^1.17.0"
datasets = "^3.5.0"
evaluate = "^0.4.3"
torch = "^2.6.0"
torchvision = "^0.21.0"
pillow = "^11.1.0"
accelerate = "^1.6.0"
pkginfo = "^1.12.1.2"
scikit-learn = "^1.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
