# Dataset configuration
dataset:

  train:
    - name: dummy
      root_dir: /Users/odunayoogundepo/Downloads/all_data/mock_training
      pdf_dir_name: pdf_inputs
      json_dir_name: json_outputs
      pipeline: &basic_pipeline
        - name: PDF2ImageStep
          target_longest_image_dim: 1288
        - name: FetchPageData
        - name: StaticLengthDocumentAnchoring
          target_anchor_text_len: 4000
        - name: FinetuningPrompt
          prompt_path: /Users/odunayoogundepo/Desktop/ocr_training/karanta-ocr/configs/prompts/open_ai_data_generation.yaml
        - name: JSONOutputFormat
        - name: InstructUserMessages
          prompt_first: true
        - name: Tokenizer
          processor: Qwen/Qwen2.5-VL-3B-Instruct

  eval:
    - name: processed_00_documents_eval_s2pdf
      root_dir: /data/olmOCR-mix-0225/processed_00_documents_eval_s2pdf/
      pipeline: *basic_pipeline