# Model Configuration
model_name_or_path: "Qwen/Qwen2.5-VL-3B-Instruct"
model_revision: main

# Dataset configuration
dataset_train:
  - name: dummy
    root_dir: /Users/odunayoogundepo/Downloads/all_data/mock_training
    pdf_dir_name: pdf_inputs
    json_dir_name: json_outputs
    pipeline:
      - name: PDF2ImageStep
        target_longest_image_dim: 1288
      - name: FetchPageData
      - name: StaticLengthDocumentAnchoring
        target_anchor_text_len: 4000
      - name: FinetuningPrompt
        prompt_path: /Users/odunayoogundepo/Desktop/ocr_training/karanta-ocr/configs/prompts/open_ai_data_generation.yaml
      - name: JSONOutputFormat
      - name: InstructUserMessages
        prompt_first: true
      - name: Tokenizer
        processor: "Qwen/Qwen2.5-VL-3B-Instruct"
        max_length: 8192

dataset_eval:
  - name: dummy
    root_dir: /Users/odunayoogundepo/Downloads/all_data/mock_training
    pdf_dir_name: pdf_inputs
    json_dir_name: json_outputs
    pipeline:
      - name: PDF2ImageStep
        target_longest_image_dim: 1288
      - name: FetchPageData
      - name: StaticLengthDocumentAnchoring
        target_anchor_text_len: 4000
      - name: FinetuningPrompt
        prompt_path: /Users/odunayoogundepo/Desktop/ocr_training/karanta-ocr/configs/prompts/open_ai_data_generation.yaml
      - name: JSONOutputFormat
      - name: InstructUserMessages
        prompt_first: true
      - name: Tokenizer
        processor: "Qwen/Qwen2.5-VL-3B-Instruct"
        max_length: 8192
dataloader_num_workers: 1
max_length: 8192

# Expertiment Configuration
exp_name: dummy
seed: 42
report_to:
  - wandb
gradient_accumulation_steps: 4
use_flash_attention: True
output_dir: /Users/odunayoogundepo/Desktop/ocr_training/karanta-ocr/runs
per_device_train_batch_size: 1
push_to_hub: true
hf_entity: taresco
reduce_loss: sum
report_to: wandb
wandb_project_name: karanta
wandb_entity: african-research-collective
logging_steps: 1
checkpointing_steps: epoch