# Model Configuration
model_name_or_path: &model_name "Qwen/Qwen2.5-VL-3B-Instruct"
model_revision: main

# Dataset configuration
dataset_train:
  - name: karanta_dictionary
    root_dir: /home/oogundep/karanta_training_data/dictionary
    pdf_dir_name: pdf
    json_dir_name: json_output
    pipeline:
      - name: PDF2ImageStep
        target_longest_image_dim: 1288
      - name: FetchMultipageData
      - name: StaticLengthDocumentAnchoring
        target_anchor_text_len: 4000
      - name: FinetuningPrompt
        prompt_path: /home/oogundep/karanta-ocr/configs/prompts/open_ai_data_generation.yaml
      - name: JSONOutputFormat
      - name: InstructUserMessages
        prompt_first: true
      - name: Tokenizer
        processor: *model_name
        max_length: 6144
  - name: karanta_legal
    root_dir: /home/oogundep/karanta_training_data/legal
    pdf_dir_name: pdf
    json_dir_name: json_output
    pipeline:
      - name: PDF2ImageStep
        target_longest_image_dim: 1288
      - name: FetchMultipageData
      - name: StaticLengthDocumentAnchoring
        target_anchor_text_len: 4000
      - name: FinetuningPrompt
        prompt_path: /home/oogundep/karanta-ocr/configs/prompts/open_ai_data_generation.yaml
      - name: JSONOutputFormat
      - name: InstructUserMessages
        prompt_first: true
      - name: Tokenizer
        processor: *model_name
        max_length: 6144
  - name: karanta_religion
    root_dir: /home/oogundep/karanta_training_data/religion
    pdf_dir_name: pdf
    json_dir_name: json_output
    pipeline:
      - name: PDF2ImageStep
        target_longest_image_dim: 1288
      - name: FetchMultipageData
      - name: StaticLengthDocumentAnchoring
        target_anchor_text_len: 4000
      - name: FinetuningPrompt
        prompt_path: /home/oogundep/karanta-ocr/configs/prompts/open_ai_data_generation.yaml
      - name: JSONOutputFormat
      - name: InstructUserMessages
        prompt_first: true
      - name: Tokenizer
        processor: *model_name
        max_length: 6144
  - name: karanta_no_type
    root_dir: /home/oogundep/karanta_training_data/no_type
    pdf_dir_name: pdf
    json_dir_name: json_output
    pipeline:
      - name: PDF2ImageStep
        target_longest_image_dim: 1288
      - name: FetchMultipageData
      - name: StaticLengthDocumentAnchoring
        target_anchor_text_len: 4000
      - name: FinetuningPrompt
        prompt_path: /home/oogundep/karanta-ocr/configs/prompts/open_ai_data_generation.yaml
      - name: JSONOutputFormat
      - name: InstructUserMessages
        prompt_first: true
      - name: Tokenizer
        processor: *model_name
        max_length: 6144
dataloader_num_workers: 1
max_length: 6144

# Experiment Configuration
exp_name: karanta_full_set_qwen_2_5_3B_vl
seed: 42
report_to:
  - wandb
gradient_accumulation_steps: 4
use_flash_attention: True
output_dir: /home/oogundep/karanta-ocr/runs
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
hf_entity: taresco
reduce_loss: sum
report_to: wandb
wandb_project_name: karanta
wandb_entity: african-research-collective
logging_steps: 100
eval_steps: 100
checkpointing_steps: epoch
use_deepspeed: true
num_train_epochs: 3
optimizer: adamw_torch
use_deepspeed: true
lr_scheduler_type: cosine
num_samples: 1000