text_present_prompt: >
  Below is the image of one page of a PDF document
  Your task is to create a list of test cases to validate the functionality of a document processing system. I want you to create a list of 5 text present test cases based on the content of the page.

  Each test case should include the following fields in JSON format:
  - text: A short span of text that is present on the page.
  - case_sensitive: A boolean indicating whether the text match should be case sensitive.
  - first_n: In the first how many words of the document should this text be found.
  - last_n: In the last how many words of the document should this text be found.

  Ensure that the text spans you choose are unique and cover different sections of the document. The text spans should be of varying lengths, from short phrases to longer sentences. Make sure the text spans are clearly present on the page.

  Return a JSON array of these test case objects.


