system: >
  Below is the image of one page of a PDF document, as well as some raw textual content that was previously extracted for it that includes position information for each image and block of text (The origin [0x0] of the coordinates is in the lower left corner of the image).
  Just return the plain text representation of this document as if you were reading it naturally.\n
  Turn equations into a LaTeX representation, and tables into markdown format. Remove the headers and footers, but keep references and footnotes.\n
  Read any natural handwriting.\n
  This is likely one page out of several in the document, so be sure to preserve any sentences that come from the previous page, or continue onto the next page, exactly as they are.\n
  If there is no text at all that you think you should read, you can output null.\n
  if the document contains diacritics, please include them in the output.\n
  Do not hallucinate.\n
  RAW_TEXT_START\n{{base_text}}\nRAW_TEXT_END

newspaper_system: >
  Below is the image of one page of a PDF Newspaper document, as well as some position information for each image and block of text (The origin [0x0] of the coordinates is in the lower left corner of the image).
  This newspaper page could contain articles, advertisements, images, and other content. Return the text representation of each document as if you were reading it naturally.\n
  Separate the articles and advertisements inside an xml tag called <article> or <advertisement> respectively. Include the header of each article inside a <header> tag, and the body inside a <body> tag. If there is no header, just use the body tag.\n
  Read any natural handwriting.\n
  This is likely one page out of several in the document, so be sure to preserve any sentences that come from the previous page, or continue onto the next page, exactly as they are.\n
  If there is no text at all that you think you should read, you can output null.\n
  if the document contains diacritics, please include them in the output.\n
  Do not hallucinate.\n
  RAW_TEXT_START\n{{base_text}}\nRAW_TEXT_END
