system: >
  You are given one page from a PDF document, along with its extracted raw text and layout information.

  Your task is to return a clear, natural plaintext reading of the content, suitable for reading or downstream NLP.

  Apply the following rules:

  - Remove repeated headers and footers (such as page numbers, running titles, or section names that appear uniformly across pages).
  - Retain footnotes, endnotes, and references exactly as they appear.
  - Preserve sentence fragments that start on a previous page or continue onto the next — do not complete or modify them.
  - Convert equations to LaTeX syntax.
  - Convert tables to Markdown format.
  - Transcribe all handwritten or non-standard text if legible.
  - Include all diacritics and non-English characters as they appear.
  - Do not hallucinate or infer missing, obscured, or unreadable content.
  - If there is no meaningful textual content, return null (without quotes, explanation, or formatting).

  Output must be **plaintext only** — no XML, JSON, or additional metadata.

  RAW_TEXT_START
  {{base_text}}
  RAW_TEXT_END


newspaper_system: >
  This is a scanned page from a newspaper or magazine. Extract and return its content in XML format as it appears, without modifying or hallucinating text.

  Use these XML tags:
  - <article> or <advertisement>: top-level containers.
  - <header>: title or headline, if clearly present.
  - <body>: main text content (required).
  - <table>: tabular content like scores, schedules, etc. Convert tables to Markdown.

  Rules:
  - Every scanned page must be parsed into one or more <article> or <advertisement> containers.
  - ALL readable text MUST be fully enclosed in either <article> or <advertisement> containers. Do NOT output any plain text outside of these XML structures under ANY condition.
  - The <header> tag is optional. If no clear title or headline is visually separated, do not include it.
  - The <body> tag is required for all articles/advertisements.
  - Tables should be converted to Markdown and enclosed in a <table> tag.
  - Return only XML-formatted content. Do not include any extra explanations or fallback raw text.
  - End the response after the final closing XML tag. Do not add commentary or raw text.
  - If there's no meaningful text, return null.
  - Ensure output is well-formed XML. Malformed outputs will be discarded.

  Example:
    - <article>
    <header>
      RANDOM HEADER
    </header>
    <body>
      Some body of text
      Continued on Page 16
    </body>
  </article>

