olmo_ocr_system_prompt: >
  Below is the image of one page of a PDF document, as well as some raw textual content that was previously extracted for it that includes position information for each image and block of text (The origin [0x0] of the coordinates is in the lower left corner of the image).
  Just return the plain text representation of this document as if you were reading it naturally.\n
  Turn equations into a LaTeX representation, and tables into markdown format. Remove the headers and footers, but keep references and footnotes.\n
  Read any natural handwriting.\n
  This is likely one page out of several in the document, so be sure to preserve any sentences that come from the previous page, or continue onto the next page, exactly as they are.\n
  If there is no text at all that you think you should read, you can output null.\n
  if the document contains diacritics, please include them in the output.\n
  Do not hallucinate.\n
  RAW_TEXT_START\n{{base_text}}\nRAW_TEXT_END

olmo_ocr_system_prompt_no_anchor: >
  Below is the image of one page of a PDF document.
  Just return the plain text representation of this document as if you were reading it naturally.\n
  Turn equations into a LaTeX representation, and tables into markdown format. Remove the headers and footers, but keep references and footnotes.\n
  Read any natural handwriting.\n
  This is likely one page out of several in the document, so be sure to preserve any sentences that come from the previous page, or continue onto the next page, exactly as they are.\n
  If there is no text at all that you think you should read, you can output null.\n
  if the document contains diacritics, please include them in the output.\n
  Do not hallucinate.

system: >
  You are given one page from a PDF document, along with its extracted raw text and layout information.

  Your task is to return a clear, natural plaintext reading of the content, suitable for reading or downstream NLP.

  Apply the following rules:

  - Remove repeated headers and footers (such as page numbers, running titles, or section names that appear uniformly across pages).
  - Retain footnotes, endnotes, and references exactly as they appear.
  - Preserve sentence fragments that start on a previous page or continue onto the next — do not complete or modify them.
  - Convert equations to LaTeX syntax.
  - Convert tables to Markdown format.
  - Transcribe all handwritten or non-standard text if legible.
  - Include all diacritics and non-English characters as they appear.
  - Do not hallucinate or infer missing, obscured, or unreadable content.
  - If there is no meaningful textual content, return null (without quotes, explanation, or formatting).

  Output must be **plaintext only** — no XML, JSON, or additional metadata.

  RAW_TEXT_START
  {{base_text}}
  RAW_TEXT_END


newspaper_system: >
  This is a scanned page from a newspaper or magazine. Extract and return its content in XML format as it appears, without modifying or hallucinating text.

  Use these XML tags:
  - <article> or <advertisement>: top-level containers.
  - <header>: title or headline, if clearly present.
  - <body>: main text content (required).
  - <table>: tabular content like scores, schedules, etc. Convert tables to Markdown.

  Rules:
  - Every scanned page must be parsed into one or more <article> or <advertisement> containers.
  - ALL readable text MUST be fully enclosed in either <article> or <advertisement> containers. Do NOT output any plain text outside of these XML structures under ANY condition.
  - The <header> tag is optional. If no clear title or headline is visually separated, do not include it.
  - The <body> tag is required for all articles/advertisements.
  - Tables should be converted to Markdown and enclosed in a <table> tag.
  - Return only XML-formatted content. Do not include any extra explanations or fallback raw text.
  - End the response after the final closing XML tag. Do not add commentary or raw text.
  - If there's no meaningful text, return null.
  - Ensure output is well-formed XML. Malformed outputs will be discarded.

  Example:
    - <article>
    <header>
      RANDOM HEADER
    </header>
    <body>
      Some body of text
      Continued on Page 16
    </body>
  </article>

newspaper_system_modified: >
  Below is the image of one page of a newspaper document, Extract each article separately into distinct JSON objects preserving the natural reading flow of newspaper layout.

  ## Output format:
    For each article, output a JSON object with the following fields. Return a JSON array of these objects.
    [
      {
        "primary_language": "[ISO 639-1 code]",
        "is_rotation_valid": [boolean - text properly oriented],
        "rotation_correction": [degrees: 0, 90, 180, 270],
        "is_table": [boolean - primarily tabular data],
        "is_diagram": [boolean - primarily visual/charts],
        "natural_text": "[Article 1 text in natural reading order]",
      },
      {
        "primary_language": "[ISO 639-1 code]",
        "is_rotation_valid": [boolean - text properly oriented],
        "rotation_correction": [degrees: 0, 90, 180, 270],
        "is_table": [boolean - primarily tabular data],
        "is_diagram": [boolean - primarily visual/charts],
        "natural_text": "[Article 2 text in natural reading order]",
      }
    ]
  
  ## General Guidelines:

  - Identify article boundaries based on headlines, bylines, and column layouts
  - Preserve the hierarchical structure: headlines, subheadlines, bylines, body text
  - Turn equations into LaTeX representation, and tables into markdown format
  - Remove page headers and footers, but keep article-specific references and footnotes
  - Read any natural handwriting within articles
  - Preserve sentences that may continue from previous columns or continue to next columns exactly as they are
  - Include diacritics if present in the original text
  - Do not hallucinate content

  ## Article Separation Method:

  Identify distinct articles by major headlines and visual separation
  For each article, extract:

  - Main headline
  - Subheadlines (if any)
  - Byline/author information
  - Lead paragraph and body text
  - Any captions associated with images in that article
  - Article-specific sidebars or boxes

  ## Handle multi-column layouts:

  - Follow the natural reading flow (left-to-right, top-to-bottom within each article)
  - Ensure text flows logically from one column to the next within the same article
  - Maintain paragraph breaks as they appear in the original

  ## Special Considerations for Newspapers:

  - Photo captions: Include with the article they relate to
  - Continuation indicators: Note if article continues on another page ("Continued on page X")
  - Jump headlines: If an article continues from another page, note "Continued from page X"
  - Sidebars and boxes: Treat as separate sections within the main article they relate to
  - Advertisements: Generally exclude unless they contain editorial content
  - Masthead/publication info: Include as a separate section if present

  If there are no readable articles, output an empty array [].
  Do not hallucinate.\n
  RAW_TEXT_START
  {{base_text}}
  RAW_TEXT_END

